### PR TITLE
Remove template duplication. Package.json updates. 

### PR DESCRIPTION
**Pull request by vascofernandes**
add scripts section to package.json
add ngMultiple directive to reduce template duplication.
add baseFrequency value object to reduce dependency on hard-coded numbers.

### CODE REVIEW

**Comment by DmitryEfimenko** [comment]
I really like the "reduce template duplication" part.
Can this PR be updated against latest code base?

**Comment by jacobscarter** [comment]
@vascofernandes plus one to @DmitryEfimenko's comment, rebase so we can get this reviewed and merged.

**Comment by vascofernandes** [comment]
Ok. I did the rebase. all my previous changes were applied to the current code base. This includes:
- update dependencies in package.json
- reduce the use of hardcoded numbers (1...6)
- cleaner template

All tests pass.

Best regards

**Comment by jacobscarter** [comment]
awesome this will be in the next release. Thank you so much!

**Comment by jacobscarter** [comment]
And I am sure I am now your worst nightmare but can you rebase one more time for me, im sorry :/

**Comment by vascofernandes** [comment]
No problem, I rebased again.

I would like to point out that it is usually not so good practice to leave the version of the dependencies in the package.json as "*". I understand that there is only dev dependencies involved here, but still, it if seems best to keep versions explicit. Therefore, my pull request includes explicit versions.

To simplify the process of updating package.json dependencies versions, I use this: https://www.npmjs.com/package/npm-check-updates

Best Regards

**Comment by jacobscarter** [comment]
@vascofernandes I had to revert your HTML template changes.  Below is what broke, if you can update the template without breaking the below areas then we can get them merged in:

If you use the `<option>` tag the `ng-model` that the `<select>` is bound to MUST contain a string.  So by removing the `ng-options` and putting a ng-repeat on an `<option>` tag causes the dropdown to not populate due to the value in the model being a number.  When you use `ng-options` the value can be a number and displays properly.

I attempted to use the following markup:

```html
            <select class="cron-select day-value"
                    ng-model="myFrequency.dayValues"
                    ng-multiple="allowMultiple"
                    ng-options="value as (value | cronDayName) for value in dayValues">
            </select>
```

but that caused the dropdown to not display the value as well.  You can experiment with this by running the `gh-pages` branch locally and changing code in there.

If we can get the template reduced and have the values still displayed we can re-merge in the new template file.

Thanks and let me know if you have any questions.

**Comment by vascofernandes** [comment]
ah! nice catch. I did not know that. A quick google and found this:

https://code.angularjs.org/1.4.7/docs/api/ng/directive/select

`.directive('convertToNumber', function() {
  return {
    require: 'ngModel',
    link: function(scope, element, attrs, ngModel) {
      ngModel.$parsers.push(function(val) {
        return parseInt(val, 10);
      });
      ngModel.$formatters.push(function(val) {
        return '' + val;
      });
    }
  };
});`

This should solve out problem.

**Pull request merged**
